### ISSUE TITLE
Is Infinity a number?

### ISSUE THREAD

**Issue by bipvanwinkle** [litixsoft/lx-valid#10]
I have a property that can have a value of infinity. I have specified the type of this property as number, but validation is failing.

**Comment by 4kochi** [comment]
Currently `Infinity` and `NaN` are treated as extra types. We could expose both types in our lib so that you can check for them. In your case it would look like this:

```
myProperty: {
  type: ['number', 'infinity']
}
```

So in that case both `Number` and `Infinity` would be valid values.

**Comment by bipvanwinkle** [comment]
Interesting. That is good to know. I'll try it out. Thanks.

**Comment by 4kochi** [comment]
Released new version `1.1.0` Now you can try it out.
