### ISSUE TITLE
How do we handle the case where object properties are named type?

### ISSUE THREAD

**Issue by bipvanwinkle** [litixsoft/lx-valid#11]
I have created a schema specifying a property of an object as type and it seems to break validation

**Comment by bipvanwinkle** [comment]
Actually, I just went to verify this and it looks like I was incorrect. I apologize.

**Comment by bipvanwinkle** [comment]
By the way, I love this library. Thanks for the time and energy that y'all put in to it.

**Comment by 4kochi** [comment]
Your welcome. We use it a lot in our own products too and it makes the validation a lot easier for us.
