### ISSUE TITLE
Support for ISO8601 formatted dates

### ISSUE THREAD

**Issue by Lomanic** [litixsoft/lx-valid#12]
The `date` and `date-time` formats don't support [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) formatted dates.

For example, `2016-04-11T18:18:10.2819403+02:00` does not match date[-time] format.

It would be great to handle this format, so I could cast the previous date string to a Date object as in the [convert example](https://github.com/litixsoft/lx-valid/blob/e009347e18f57764207530f007c93b9b04a5367d/README.md#convert-option).

Currently I can validate my JSON against this format with [this snippet](https://tonicdev.com/570d1ccfa9faf3130037d992/570d1ccfa9faf3130037d993) (using the isDate function from [validator](https://www.npmjs.com/package/validator/) lib), but it isn't converted to a Date in the same pass.

I tried to add a new format using the `extendFormat` function, but casting to Date in `convert` does not seem to work with my custom format ([tonicdev snippet](https://tonicdev.com/570d1588d5cdb011003954d2/570d1588d5cdb011003954d3)).

**Comment by 4kochi** [comment]
The method `extendFormat()` works fine for me. But your input does not match the given ISO8601 regex. Therefore the validations is invalid and the convert function is not triggered.
