### ISSUE TITLE
lx-valid: option "deleteUnknownProperties" is deprcated. It will be removed in version 0.5.0! Please use option "unknowProperties" instead.

### ISSUE THREAD

**Issue by steowens** [litixsoft/lx-valid#5]
Whenever I run a validation I get this message. What does it mean?  How do I fix it so it doesn't occur?

**Comment by 4kochi** [comment]
Well, the option "deleteUnknownProperties" is still in the defaults. I will remove it and the message will go away.

**Comment by steowens** [comment]
Awesome!  Any idea when the update will be available via npm install?
