### ISSUE TITLE
asyncValidate seems to be pointless

### ISSUE THREAD

**Issue by ilearnio** [litixsoft/lx-valid#9]
Your plugin is great, I have just started to use it and I'm very satisfied.

But there is one thing that seems to be pointless in lx-valid, its asynchronous functionality.
In your tests https://github.com/litixsoft/lx-valid/blob/master/test/tests.spec.js#L1208, you are running two synchronous (not asynchronous!) functions through `async.parallel`, which makes no sense. It will run both of them one after another anyway in a single tick.

Parallels would only work if they could fire both functions at a time, then wait, then execute one of the callbacks (of the function that is finished its job first), then wait again, and then triggers a callback of the second finished async function. But there is no any "wait" thing between running of two synchronous functions

**Comment by 4kochi** [comment]
Yeah right, maybe the example isn't quite good. But I can tell that it works. You can find a real world example here:

https://github.com/litixsoft/baboon-backend/blob/master/api/auth/repositories/usersRepository.js

**Comment by ilearnio** [comment]
Now I see. Then it's a really powerful feature, I'm taking my words back. Thank you!
